### ISSUE TITLE
Multiple clients

### ISSUE THREAD

**Issue by liorr-cloudride** [ufukty/ovpn-auth#2]
how to create multiple clients secrets yaml?

**Comment by ufukty** [comment]
Multiple users with differing credentials are not supported by ovpn-auth at the moment. But the idea is great. We can work on a merge if anyone interested on sending PR.

I'm gonna close #1  since it doesn't involve a code to merge.

**Comment by ufukty** [comment]
v1.0.0 brings multiple user support.

**Comment by ufukty** [comment]
v1.0.0 brings multiple user support to ovpn-auth
